basetable:
  index: indices.csv
  file: basetable.csv
  type: csv
  threshold: 0
disaggregation:
  - id: ARG
    type: region
    into: [Ciudad_de_Buenos_Aires, Buenos_Aires, Catamarca, Cordoba, Corrientes, Chaco, Chubut, Entre_Rios, Formosa, Jujuy, La_Pampa, La_Rioja, Mendoza, Misiones, Neuquen, Rio_Negro, Salta, San_Juan, San_Luis, Santa_Cruz, Santa_Fe, Santiago_del_Estero, Tucuman, Tierra_del_Fuego]
    proxies:
      - level: 2
        year: 2016
        file: proxy_reg_arg.csv
output:
  file: output.csv
  type: csv
  